version: "3.7"

services:
  api:
    build: 
      context: ./api
    container_name: api
    environment:
      - CONNECTION_STRING=postgres://postgres:postgres@db/postgres_db
    depends_on:
      - postgres-db
    networks:
      - Public-comunicate
      - Privet-comunicate

  web:
    build: 
      context: ./web
    container_name: web
    environment:
      - API_URL=http://api:3001/data
    command: node index.js
    volumes:
      - ./web:/web
    ports:
      - "80:3000"
    depends_on:
      - api
    networks:
      - Public-comunicate
 

  postgres-db:
    image: postgres:11.2-alpine
    # ports: ["5432"]
    # container_name: postgres-db
    environment:
      POSTGRES_USER: "raghad"
      POSTGRES_PASSWORD: "1234"
      POSTGRES_DB: "RGpostgres_db"
    volumes:
      - ./sql_scripts/:/docker-entrypoint-initdb.d
    networks:
      - Privet-comunicate
    
networks:
  Public-comunicate:
      driver: bridge
      ipam:
        config:
          - subnet: 182.1.0.0/16
  Privet-comunicate:
      driver: bridge
      ipam:
        config:
          - subnet: 182.2.0.0/16